<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PersonMappingRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class PersonMappingRepository extends DocumentRepository
{
	public function getPersonInfo()
    {
        return $this->createQueryBuilder()
        ->select('firstName', 'lastName', 'personAge')
        ->getQuery()
        ->execute();
    }
   # public function setPersonInfo($persons)
   #{
      	    # return $this->createQueryBuilder()
          #->insert($person)
          #->getQuery()
          #->execute();
     
   # }
	public function findCount()
    {
        return $this->createQueryBuilder()
        ->count('firstName')
        ->getQuery()
        ->execute();
    }
}
