app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#_home:
#  resource: "@AppBundle/Controller/MainController.php"
#  type: annotation
#  prefix: /home

_index:
  path: /index
  defaults: { _controller: AppBundle:Main:index }

_setup:
  path: /setup
  defaults: { _controller: AppBundle:Setup:setup }  

_test:
  path: /test
  defaults: { _controller: AppBundle:Test:generate } 

_transfer:
  path: /transfer
  defaults: { _controller: AppBundle:Transfer:move } 

_count:
  path: /count
  defaults: { _controller: AppBundle:Count:count }

_takedown:
  path: /takedown
  defaults: { _controller: AppBundle:Takedown:take }

_teardown:
 path: /teardown
 defaults: { _controller: AppBundle:Teardown:tear }

